# Generated by Django 3.2.21 on 2023-09-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Wastes', '0008_auto_20230930_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('logo', models.ImageField(upload_to='', verbose_name='Image')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('waste_types', models.ManyToManyField(to='Wastes.WasteTypes', verbose_name='Types of wastes')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('text', models.TextField(verbose_name='Text')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
