# Generated by Django 3.2.21 on 2023-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.ImageField(upload_to='', verbose_name='Waste type icon')),
            ],
        ),
        migrations.CreateModel(
            name='WasteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('lattitude', models.FloatField(verbose_name='Lattitude')),
                ('waste_type', models.ManyToManyField(to='Wastes.WasteTypes', verbose_name='Type of waste')),
            ],
        ),
        migrations.CreateModel(
            name='WasteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Wast name')),
                ('photo', models.ImageField(upload_to='', verbose_name='Waste image')),
                ('recomendation', models.TextField(verbose_name='Recomendation for util. ')),
                ('waste_type', models.ManyToManyField(to='Wastes.WasteTypes', verbose_name='Type of waste')),
            ],
        ),
    ]
