# Generated by Django 3.2.21 on 2023-09-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0002_auto_20230922_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteinfo',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Waste image'),
        ),
    ]
