# Generated by Django 3.2.21 on 2023-09-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0005_auto_20230922_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteinfo',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='wasteinfo',
            name='waste_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wastes.wastetypes'),
        ),
        migrations.RemoveField(
            model_name='wastesite',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='wastesite',
            name='waste_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wastes.wastetypes'),
        ),
    ]
