# Generated by Django 3.2.21 on 2023-09-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0007_auto_20230930_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastesite',
            name='geo_pos',
        ),
        migrations.AddField(
            model_name='wastesite',
            name='lattitude',
            field=models.FloatField(default=0, verbose_name='Lattitude'),
        ),
        migrations.AddField(
            model_name='wastesite',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude'),
        ),
    ]
