# Generated by Django 3.2.21 on 2023-11-17 06:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0009_auto_20231021_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteexample',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static', location=None), upload_to='', verbose_name='Waste image'),
        ),
    ]
