# Generated by Django 3.2.21 on 2023-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0010_wasteexample_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetypes',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/waste_type_icon/', verbose_name='Waste type icon'),
        ),
        migrations.AlterField(
            model_name='wasteexample',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/waste_example_photo/', verbose_name='Waste image'),
        ),
    ]
