# Generated by Django 3.2.21 on 2023-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(auto_created=True, blank=True, max_length=255, verbose_name='User name'),
        ),
    ]
