# Generated by Django 3.2.21 on 2023-09-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteinfo',
            name='waste_type',
        ),
        migrations.RemoveField(
            model_name='wastesite',
            name='waste_type',
        ),
        migrations.RemoveField(
            model_name='wastetypes',
            name='name',
        ),
        migrations.AddField(
            model_name='wastetypes',
            name='type',
            field=models.CharField(default='type', max_length=100, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='wastetypes',
            name='description',
            field=models.TextField(default='description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wastetypes',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Waste type icon'),
        ),
    ]
