# Generated by Django 3.2.21 on 2023-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0003_alter_wasteinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Waste image'),
        ),
        migrations.AlterField(
            model_name='wastetypes',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Waste type icon'),
        ),
    ]
