# Generated by Django 3.2.21 on 2023-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0004_auto_20230922_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteinfo',
            name='waste_type',
            field=models.ManyToManyField(to='Wastes.WasteTypes'),
        ),
        migrations.AddField(
            model_name='wastesite',
            name='waste_type',
            field=models.ManyToManyField(to='Wastes.WasteTypes'),
        ),
    ]
