# Generated by Django 3.2.21 on 2023-09-29 22:55

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Wastes', '0006_auto_20230922_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Wast name')),
                ('description', models.TextField(verbose_name='Desc')),
            ],
        ),
        migrations.RemoveField(
            model_name='wastesite',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='wastesite',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='wastetypes',
            name='icon',
        ),
        migrations.AddField(
            model_name='wastesite',
            name='geo_pos',
            field=geoposition.fields.GeopositionField(default=(111, 11), max_length=42),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='wastesite',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='wastesite',
            name='waste_type',
            field=models.ManyToManyField(to='Wastes.WasteTypes'),
        ),
        migrations.DeleteModel(
            name='WasteInfo',
        ),
        migrations.AddField(
            model_name='wasteexample',
            name='waste_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wastes.wastetypes'),
        ),
    ]
